In [1]:
import numpy as np
import damask
result_file = "../IMI817_34um_tensionY.hdf5"

In [2]:
result = damask.Result(result_file)

In [3]:
result

Created by DAMASK_grid v3.0.0-alpha7
        on 2023-03-29 12:27:08+0530
 executing "DAMASK_grid --load tensionY.yaml --geom IMI817_34um.vti"

increment_0 (0.0 s)
  phase
    IMI817
      mechanical
        F / 1: deformation gradient
        F_e / 1: elastic deformation gradient
        F_p / 1: plastic deformation gradient
        IPFcolor_(0 0 1) / 8-bit RGB: Inverse Pole Figure (IPF) colors along sample direction (0 0 1)
        L_p / 1/s: plastic velocity gradient
        O / q_0 (q_1 q_2 q_3): crystal orientation as quaternion
        P / Pa: first Piola-Kirchhoff stress
        epsilon_V^0.0(F) / 1: strain tensor of F (deformation gradient)
        epsilon_V^0.0(F)_vM / 1: Mises equivalent strain of epsilon_V^0.0(F) (strain tensor of F (deformation gradient))
        gamma_sl / 1: plastic shear
        sigma / Pa: Cauchy stress calculated from P (first Piola-Kirchhoff stress) and F (deformation gradient)
        sigma_vM / Pa: Mises equivalent stress of sigma (Cauchy stress calc

In [4]:
result = result.view(increments=-1)
result

Created by DAMASK_grid v3.0.0-alpha7
        on 2023-03-29 12:27:08+0530
 executing "DAMASK_grid --load tensionY.yaml --geom IMI817_34um.vti"

increment_696 (61.600000000001 s)
  phase
    IMI817
      mechanical
        F / 1: deformation gradient
        F_e / 1: elastic deformation gradient
        F_p / 1: plastic deformation gradient
        IPFcolor_(0 0 1) / 8-bit RGB: Inverse Pole Figure (IPF) colors along sample direction (0 0 1)
        L_p / 1/s: plastic velocity gradient
        O / q_0 (q_1 q_2 q_3): crystal orientation as quaternion
        P / Pa: first Piola-Kirchhoff stress
        epsilon_V^0.0(F) / 1: strain tensor of F (deformation gradient)
        epsilon_V^0.0(F)_vM / 1: Mises equivalent strain of epsilon_V^0.0(F) (strain tensor of F (deformation gradient))
        gamma_sl / 1: plastic shear
        sigma / Pa: Cauchy stress calculated from P (first Piola-Kirchhoff stress) and F (deformation gradient)
        sigma_vM / Pa: Mises equivalent stress of sigma (Cauc

In [5]:
stress = result.get("sigma_vM")
stress

array([8.73979390e+08, 9.40335004e+08, 8.87489323e+08, ...,
       8.56974804e+08, 8.82522982e+08, 1.05050107e+09])

In [6]:
strain = result.get('epsilon_V^0.0(F)_vM')
strain

array([0.09052343, 0.10688512, 0.05948424, ..., 0.04950507, 0.07703575,
       0.15087738])

In [7]:
texture = result.get("O")
print(texture.shape)
texture

(141688, 4)


array([[ 3.02438497e-01,  9.04000535e-01,  3.01836974e-01,
        -1.44370851e-02],
       [ 3.07291248e-01,  8.97238816e-01,  3.17071788e-01,
         2.77860702e-04],
       [ 3.07501848e-01,  9.00970038e-01,  3.06028582e-01,
        -6.48926775e-03],
       ...,
       [ 2.77944420e-01,  8.35629831e-01,  4.72696045e-01,
        -3.20645398e-02],
       [ 2.75367514e-01,  8.36589312e-01,  4.72858206e-01,
        -2.63850561e-02],
       [ 9.99427701e-01, -7.00783921e-04, -4.82170903e-03,
        -3.34743179e-02]])

In [8]:
texture_quaternions = damask.Orientation.from_quaternion(q=texture, lattice="hP")
texture_quaternions

Crystal family: hexagonal
Bravais lattice: hP
a=1 m, b=1 m, c=1.633 m
α=90°, β=90°, γ=120°
Quaternions of shape (141688,)
[[ 3.02438497e-01  9.04000535e-01  3.01836974e-01 -1.44370851e-02]
 [ 3.07291248e-01  8.97238816e-01  3.17071788e-01  2.77860702e-04]
 [ 3.07501848e-01  9.00970038e-01  3.06028582e-01 -6.48926775e-03]
 ...
 [ 2.77944420e-01  8.35629831e-01  4.72696045e-01 -3.20645398e-02]
 [ 2.75367514e-01  8.36589312e-01  4.72858206e-01 -2.63850561e-02]
 [ 9.99427701e-01 -7.00783921e-04 -4.82170903e-03 -3.34743179e-02]]

In [9]:
euler = texture_quaternions.as_Euler_angles()
euler

array([[0.27455231, 2.52637015, 5.9132342 ],
       [0.34059249, 2.51690191, 5.94440127],
       [0.30633873, 2.51631563, 5.93464648],
       ...,
       [0.39994368, 2.57444642, 5.65353081],
       [0.4189284 , 2.58102439, 5.67320496],
       [4.53457927, 0.00974478, 1.6816441 ]])

In [10]:
texture_euler = damask.Rotation(texture).as_Euler_angles()
texture_euler

array([[0.27455231, 2.52637015, 5.9132342 ],
       [0.34059249, 2.51690191, 5.94440127],
       [0.30633873, 2.51631563, 5.93464648],
       ...,
       [0.39994368, 2.57444642, 5.65353081],
       [0.4189284 , 2.58102439, 5.67320496],
       [4.53457927, 0.00974478, 1.6816441 ]])

In [21]:
original_data_file = "../Preprocessing/IMI817_34um_coarse_clean.ang"
header_lines_in_original = 26
export_file_name = "../PostDeformedTexture.ang"
IQ_index = 5
CI_index = 6

In [22]:
header = []
data_lines = []
with open(original_data_file, "r") as file:
    all_data = file.readlines()
    for i in range(header_lines_in_original):
        header.append(all_data[i])
    for i in range(header_lines_in_original, len(all_data)):
        data_lines.append(all_data[i].split())
print(header)


['# TEM_PIXperUM          1.000000\n', '# x-star                0.500000\n', '# y-star                0.500000\n', '# z-star                0.500000\n', '# WorkingDistance       20.000000\n', '#\n', '# Phase 1\n', '# MaterialName  \tTitanium-Hexagonal\n', '# Formula     \t\n', '# Info\t\t\t\tZ. Metallkd. [ZEMTAE], vol. 59, page 377\n', '# Symmetry              62\n', '# LatticeConstants      2.950 2.950 4.681  90.000  90.000 120.000\n', '# NumberFamilies        0\n', '# GRID: SqrGrid\n', '# XSTEP: 2.000000\n', '# YSTEP: 2.000000\n', '# NCOLS_ODD: 398\n', '# NCOLS_EVEN: 398\n', '# NROWS: 356\n', '#\n', '# OPERATOR: \t\n', '#\n', '# SAMPLEID: \t\n', '#\n', '# SCANID: \t\n', '#\n']


In [23]:
data_lines

[['0.32848',
  '2.52079',
  '5.97242',
  '0.00000',
  '0.00000',
  '133.0',
  '1.000',
  '0',
  '0',
  '0.552',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.34527',
  '2.51758',
  '5.98454',
  '2.00000',
  '0.00000',
  '122.0',
  '0.875',
  '0',
  '0',
  '0.568',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.35106',
  '2.51791',
  '5.99067',
  '4.00000',
  '0.00000',
  '124.0',
  '1.000',
  '0',
  '0',
  '0.676',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.34154',
  '2.51744',
  '5.98273',
  '6.00000',
  '0.00000',
  '108.0',
  '0.875',
  '0',
  '0',
  '0.630',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.31826',
  '2.51594',
  '5.95225',
  '8.00000',
  '0.00000',
  '91.0',
  '0.750',
  '0',
  '0',
  '0.798',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['3.19635',
  '2.68590',
  '2.32860',
  '10.00000',
  '0.00000',
  '88.0',
  '0.875',
  '0',
  '0',
  '0.867',
  '0.000000',
  '0.000000',
  '0.000000',
  

In [28]:
# Updating data lines
for i, data in enumerate(data_lines):
    for j in range(3):
        data[j] = str(round(texture_euler[i][j], 6))
    data[IQ_index] = str(round(strain[i], 6))
    data[CI_index] = str(round(stress[i], 3))
data_lines

[['0.274552',
  '2.52637',
  '5.913234',
  '0.00000',
  '0.00000',
  '0.090523',
  '873979390.199',
  '0',
  '0',
  '0.552',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.340592',
  '2.516902',
  '5.944401',
  '2.00000',
  '0.00000',
  '0.106885',
  '940335004.062',
  '0',
  '0',
  '0.568',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.306339',
  '2.516316',
  '5.934646',
  '4.00000',
  '0.00000',
  '0.059484',
  '887489323.265',
  '0',
  '0',
  '0.676',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.311077',
  '2.517954',
  '5.921613',
  '6.00000',
  '0.00000',
  '0.059969',
  '856290692.748',
  '0',
  '0',
  '0.630',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['0.264385',
  '2.514245',
  '5.875275',
  '8.00000',
  '0.00000',
  '0.067075',
  '863627593.536',
  '0',
  '0',
  '0.798',
  '0.000000',
  '0.000000',
  '0.000000',
  '0.000000'],
 ['3.172698',
  '2.71098',
  '2.335415',
  '10.00000',
  '0.00000',
  '0.041984',
  '9

In [29]:
# Save the data as ang
with open(export_file_name, "w") as write_file:
    for line in header:
        write_file.write(line)
    for data in data_lines:
        line = ""
        for datas in data:
            line += datas
            line += "\t"
        write_file.write(line + "\n")

In [30]:
result.export_VTK()